name = "matjip-finder-api"
main = "worker.js"
compatibility_date = "2026-09-01"

[vars]
ALLOW_ORIGIN = "https://yjjn2005.github.io"

[[kv_namespaces]]
binding = "MATJIP_SYNC"
id = "13afd1e3b195453eba451bdca5a0476d"
